#! /usr/bin/python

import unittest
import sys
sys.path.append("../../pycat")
import log
_LOGGER = log.getLogger("log.test")
_LOGGER2 = log.getLogger("log.test2")

class LogTestCase(unittest.TestCase):
    def testLogger(self):
        logger = log.getLogger("log")
        _LOGGER.debug("debug")
        _LOGGER.info("info")
        _LOGGER.warning("warning")
        _LOGGER.error("error")
        _LOGGER2.debug("debug")
        _LOGGER2.info("info")
        _LOGGER2.warning("warning")
        _LOGGER2.error("error")
        logger.setProcess("process-1")
        _LOGGER.debug("debug")
        _LOGGER.info("info")
        _LOGGER.warning("warning")
        _LOGGER.error("error")
        _LOGGER2.debug("debug")
        _LOGGER2.info("info")
        _LOGGER2.warning("warning")
        _LOGGER2.error("error")
        logger.setStage("stage-1")
        _LOGGER.debug("debug")
        _LOGGER.info("info")
        _LOGGER.warning("warning")
        _LOGGER.error("error")
        _LOGGER2.debug("debug")
        _LOGGER2.info("info")
        _LOGGER2.warning("warning")
        _LOGGER2.error("error")
        logger.setCycle("cycle-1")
        _LOGGER.debug("debug")
        _LOGGER.info("info")
        _LOGGER.warning("warning")
        _LOGGER.error("error")
        _LOGGER2.debug("debug")
        _LOGGER2.info("info")
        _LOGGER2.warning("warning")
        _LOGGER2.error("error")
        logger.setItem("item-1")
        _LOGGER.debug("debug")
        _LOGGER.info("info")
        _LOGGER.warning("warning")
        _LOGGER.error("error")
        _LOGGER2.debug("debug")
        _LOGGER2.info("info")
        _LOGGER2.warning("warning")
        _LOGGER2.error("error")

if __name__ == "__main__":
    log.config()
    unittest.main()
